import 'dart:async';

import 'package:base_ui_flutter/base_ui_flutter.dart';
import 'package:flutter/gestures.dart' show kSecondaryButton;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show LogicalKeyboardKey, SystemChannels;
import 'package:flutter_test/flutter_test.dart';
import 'package:provider/provider.dart';
import 'package:re_editor/re_editor.dart';
import 'package:daro/app/app_state.dart';
import 'package:daro/data/table_design.dart';
import 'package:daro/widgets/table_designer_page.dart';

void main() {
  // 与 main.dart 同构:AppState 在 MaterialApp 之上,根导航器弹出的
  // Dialog(showDialog 默认 useRootNavigator)才能取到主题色板。
  Widget harness() => ChangeNotifierProvider(
        create: (_) => AppState(),
        child: MaterialApp(
          theme: ThemeData(brightness: Brightness.dark),
          home: Material(
            type: MaterialType.transparency,
            child: const TableDesignerPage(
              title: '新建表',
              connection: '无此连接',
              database: 'db',
            ),
          ),
        ),
      );

  testWidgets('TableDesignerPage 11 个标签布局无异常', (tester) async {
    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();

    // 11 个标签齐全
    for (final label in ['字段', '索引', '外键', '唯一键', '检查', '排除', '规则', '触发器', '选项', '注释', 'SQL 预览']) {
      expect(find.text(label), findsWidgets, reason: '缺少标签: $label');
    }
    // 默认预置一行字段
    expect(find.text('添加字段'), findsOneWidget);
    expect(find.text('保存'), findsOneWidget);
  });

  testWidgets('添加字段按钮与字段行编辑', (tester) async {
    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();

    await tester.tap(find.text('添加字段'));
    await tester.pumpAndSettle();
    // 插入 / 删除按钮出现(行数 ≥ 1 时删除可用)
    expect(find.text('插入字段'), findsOneWidget);
    expect(find.text('删除字段'), findsOneWidget);
    // 上移在第一行禁用、下移可用
    expect(find.text('上移'), findsOneWidget);
  });

  testWidgets('切换到 SQL 预览标签渲染 DDL', (tester) async {
    // 11 个标签超宽,放大窗口让「SQL 预览」标签可见
    tester.view.physicalSize = const Size(1800, 1000);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);

    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();

    await tester.tap(find.text('SQL 预览'));
    await tester.pumpAndSettle();
    // 已切换到预览标签:提示条出现(re_editor 内容为自绘文本,find.text 不可见)
    expect(find.textContaining('将按以下顺序执行'), findsOneWidget);
  });

  testWidgets('字段页底部属性面板为纵向多行(含 IDENTITY 属性)', (tester) async {
    tester.view.physicalSize = const Size(1800, 1000);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);

    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();

    // 默认连接类型 PostgreSQL:虚拟类型 + 完整序列属性均展示
    for (final label in ['默认', '排序规则', '维度', '虚拟类型', '递增', '最小', '最大', '开始值', '缓存', '循环']) {
      expect(find.text(label), findsWidgets, reason: '属性面板缺少: $label');
    }
    // 未开启 IDENTITY 时虚拟类型显示为「无」
    expect(find.text('无'), findsOneWidget);
  });

  testWidgets('主键下拉设置后键列出现钥匙图标与序号', (tester) async {
    tester.view.physicalSize = const Size(1800, 1000);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);

    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();

    // 初始无主键:仅工具栏「主键 ▾」上一个钥匙图标
    expect(find.byIcon(Icons.key), findsNWidgets(1));

    await tester.tap(find.text('主键'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('设置主键'));
    await tester.pumpAndSettle();

    // 键列出现 钥匙 + 序号 1
    expect(find.byIcon(Icons.key), findsNWidgets(2));
    expect(find.text('1'), findsWidgets);
  });

  testWidgets('选「GENERATED BY DEFAULT AS IDENTITY」预填序列默认值', (tester) async {
    tester.view.physicalSize = const Size(1800, 1000);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);

    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();

    await tester.tap(find.text('无'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('GENERATED BY DEFAULT AS IDENTITY').last);
    await tester.pumpAndSettle();

    // 下拉收起后当前值回显
    expect(find.text('GENERATED BY DEFAULT AS IDENTITY'), findsWidgets);
  });

  // ── 设计表(编辑模式) ─────────────────────────────────────
  // `connection: '无此连接'` 下无真实驱动,编辑模式经 [TableDesignerPage.designLoader]
  // 注入反查结果;此时 _typeId 落回默认的 postgresql。

  DesignTable readBack() => DesignTable()
    ..name = 'configs'
    ..schema = 'public'
    ..pkName = 'configs_pkey'
    ..columns.addAll([
      DesignColumn(
          name: 'id',
          type: 'int8',
          length: '64',
          notNull: true,
          primaryKey: true),
      DesignColumn(name: 'name', type: 'varchar', length: '32', comment: '名称'),
    ]);

  Widget editHarness(
          {Future<DesignTable?> Function(String, String, String?)? loader}) =>
      ChangeNotifierProvider(
        create: (_) => AppState(),
        child: MaterialApp(
          theme: ThemeData(brightness: Brightness.dark),
          home: Material(
            type: MaterialType.transparency,
            child: TableDesignerPage(
              title: 'configs (设计)',
              connection: '无此连接',
              database: 'db',
              schema: 'public',
              existingTable: 'configs',
              designLoader: loader,
            ),
          ),
        ),
      );

  /// 打开 → 加载占位帧 → 回填帧。
  /// 加载占位里的 Spinner 是无限动画,这一段不能用 pumpAndSettle。
  Future<void> openEdit(WidgetTester tester, Widget page) async {
    await tester.pumpWidget(page);
    await tester.pump();
    await tester.pump();
  }

  bool saveEnabled(WidgetTester tester) => tester
      .widget<ToolbarButton>(find.widgetWithText(ToolbarButton, '保存'))
      .enabled;

  String previewSql(WidgetTester tester) =>
      tester.widget<CodeEditor>(find.byType(CodeEditor)).controller!.text;

  testWidgets('编辑模式:反查结果回填网格与表名,无变更时禁保存', (tester) async {
    tester.view.physicalSize = const Size(1800, 1000);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);

    await openEdit(tester, editHarness(loader: (db, t, s) async => readBack()));

    expect(find.text('configs'), findsOneWidget); // 表名输入框预填
    expect(find.text('id'), findsOneWidget); // 首行列名
    expect(find.text('64'), findsOneWidget); // int8 长度格显示位宽
    expect(find.text('32'), findsOneWidget);
    // 注释列回填(与表头「名称」同名,限定在行内比)
    expect(
      find.descendant(of: find.byType(ListView), matching: find.text('名称')),
      findsOneWidget,
    );
    expect(find.text('varchar'), findsWidgets); // 类型下拉回显
    expect(find.byIcon(Icons.arrow_right), findsOneWidget); // ▶ 当前行标记
    expect(find.textContaining('— 设计'), findsOneWidget); // 标题条区分两种模式
    expect(find.text('无变更'), findsOneWidget);
    expect(saveEnabled(tester), isFalse); // 无变更不可保存
    // PG / SQL Server 无对应 ALTER,列序动作置灰并提示
    expect(find.text('调整已有列的顺序仅 MySQL / MariaDB 支持'), findsOneWidget);
  });

  testWidgets('编辑模式:加载中占位,完成后消失', (tester) async {
    tester.view.physicalSize = const Size(1800, 1000);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);

    final completer = Completer<DesignTable?>();
    await tester.pumpWidget(
        editHarness(loader: (db, t, s) => completer.future));
    await tester.pump();

    expect(find.textContaining('正在加载 configs 的结构'), findsOneWidget);
    expect(find.byType(Spinner), findsWidgets);
    expect(find.text('id'), findsNothing); // 结构未就位前不渲染空网格

    completer.complete(readBack());
    await tester.pump();
    await tester.pump();

    expect(find.textContaining('正在加载 configs 的结构'), findsNothing);
    expect(find.byType(Spinner), findsNothing);
    expect(find.text('id'), findsOneWidget);
  });

  testWidgets('编辑模式:改一格 → 已修改 + 保存可点 + 预览出 ALTER', (tester) async {
    tester.view.physicalSize = const Size(1800, 1000);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);

    await openEdit(tester, editHarness(loader: (db, t, s) async => readBack()));

    // 第 2 行「不是 null」勾选
    await tester.tap(find
        .descendant(of: find.byType(ListView), matching: find.byType(CheckBox))
        .at(1));
    await tester.pump();

    expect(find.text('已修改'), findsOneWidget);
    expect(saveEnabled(tester), isTrue);

    await tester.tap(find.text('SQL 预览'));
    await tester.pumpAndSettle();
    expect(
      previewSql(tester),
      'ALTER TABLE "public"."configs" ALTER COLUMN "name" SET NOT NULL;',
    );
  });

  testWidgets('编辑模式:无变更时预览输出说明行而非空白', (tester) async {
    tester.view.physicalSize = const Size(1800, 1000);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);

    await openEdit(tester, editHarness(loader: (db, t, s) async => readBack()));
    await tester.tap(find.text('SQL 预览'));
    await tester.pumpAndSettle();

    expect(previewSql(tester), '-- 没有待应用的变更');
    expect(saveEnabled(tester), isFalse);
  });

  testWidgets('编辑模式:驱动不支持反查 → 只读降级', (tester) async {
    tester.view.physicalSize = const Size(1800, 1000);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);

    await openEdit(tester, editHarness(loader: (db, t, s) async => null));

    expect(find.textContaining('暂不支持编辑已有表结构'), findsOneWidget);
    expect(find.text('只读'), findsOneWidget);
    expect(saveEnabled(tester), isFalse);
    // 表名输入框禁用(不可改名 → 不会生成 RENAME)
    expect(tester.widget<Input>(find.byType(Input).first).enabled, isFalse);
    // 动作按钮整组置灰
    expect(
      tester
          .widget<IgnorePointer>(find
              .ancestor(
                  of: find.text('添加字段'), matching: find.byType(IgnorePointer))
              .first)
          .ignoring,
      isTrue,
    );
  });

  testWidgets('编辑模式:反查失败 → 错误文案 + 重试', (tester) async {
    tester.view.physicalSize = const Size(1800, 1000);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);

    var calls = 0;
    await openEdit(tester, editHarness(loader: (db, t, s) async {
      calls++;
      throw StateError('relation "configs" does not exist');
    }));

    expect(find.textContaining('读取 configs 结构失败'), findsOneWidget);
    expect(find.textContaining('does not exist'), findsWidgets);
    expect(find.text('id'), findsNothing); // 不能静默降级成一张空表
    expect(saveEnabled(tester), isFalse);

    await tester.tap(find.text('重试'));
    await tester.pump();
    await tester.pump();
    expect(calls, 2);
  });

  // ── 参考工具对齐:索引字段弹窗 / 外键注释列 / 触发器子页 / 选项 / 注释 ──

  /// 放大窗口:多列表格与 900×520 的「选择数据表字段」弹窗都要放得下
  void wideView(WidgetTester tester) {
    tester.view.physicalSize = const Size(1900, 1200);
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.reset);
  }

  /// 切标签:点标签条上的文本(标签条在内容之前,故取首个匹配)
  Future<void> openTab(WidgetTester tester, String label) async {
    await tester.tap(find.text(label).first);
    await tester.pumpAndSettle();
    expect(tester.takeException(), isNull, reason: '切到「$label」标签时报错');
  }

  testWidgets('11 个标签逐个切换都能渲染(表头与列宽不成套即崩)', (tester) async {
    wideView(tester);
    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();

    for (final label in [
      '索引',
      '外键',
      '唯一键',
      '检查',
      '排除',
      '规则',
      '触发器',
      '选项',
      '注释',
      'SQL 预览',
      '字段',
    ]) {
      await openTab(tester, label);
    }
  });

  testWidgets('索引「字段」格的 ... 打开「选择数据表字段」,确定后回写字段', (tester) async {
    wideView(tester);
    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();

    // 弹窗行来源是表字段:先建一个名为 amount 的字段
    await tester.tap(find.text('添加字段'));
    await tester.pumpAndSettle();
    await tester.enterText(
      find.descendant(
          of: find.byType(ListView), matching: find.byType(TextField)).first,
      'amount',
    );
    await tester.pump();

    await openTab(tester, '索引');
    await tester.tap(find.text('添加索引'));
    await tester.pumpAndSettle();
    expect(find.text('...'), findsOneWidget); // 字段格右侧的 `...`

    await tester.tap(find.text('...'));
    await tester.pumpAndSettle();
    expect(find.text('选择数据表字段'), findsOneWidget);
    for (final h in [
      '排序规则模式',
      '排序规则',
      '运算符类别模式',
      '运算符类别',
      '排序顺序',
      'Nulls 排序',
    ]) {
      expect(find.text(h), findsOneWidget, reason: '弹窗缺少列: $h');
    }

    // 「+」把当前行加入索引 → 确定
    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();
    await tester.tap(find.text('确定'));
    await tester.pumpAndSettle();
    expect(find.text('选择数据表字段'), findsNothing);
    expect(find.text('amount'), findsWidgets);

    // 回写进了模型:预览能生成带该字段的索引语句
    await openTab(tester, 'SQL 预览');
    expect(previewSql(tester), allOf(contains('CREATE INDEX'), contains('("amount")')));
  });

  testWidgets('外键网格有「注释」列,底部保留 符合全部 / 可延迟 / 延迟', (tester) async {
    wideView(tester);
    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();

    await openTab(tester, '外键');
    await tester.tap(find.text('添加外键'));
    await tester.pumpAndSettle();

    for (final h in ['被引用的模式', '被引用的表（父）', '被引用的字段', '删除时', '更新时']) {
      expect(find.text(h), findsOneWidget, reason: '外键网格缺少列: $h');
    }
    // 「注释」= 标签条 + 外键表头 + 空单元格 hint
    expect(find.text('注释'), findsNWidgets(3));
    expect(find.text('符合全部'), findsOneWidget);
    expect(find.text('可延迟'), findsOneWidget);

    // 注释格确实写进模型:预览生成 COMMENT ON CONSTRAINT
    final cells = find.descendant(
        of: find.byType(ListView), matching: find.byType(TextField));
    await tester.enterText(cells.first, 'fk_x');
    await tester.pump();
    await tester.enterText(cells.last, '引用用户');
    await tester.pump();

    await openTab(tester, 'SQL 预览');
    expect(
      previewSql(tester),
      contains('COMMENT ON CONSTRAINT "fk_x" ON "Untitled" IS \'引用用户\';'),
    );
  });

  testWidgets('触发器属性面板分「常规 / 约束」两个子页', (tester) async {
    wideView(tester);
    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();

    await openTab(tester, '触发器');
    await tester.tap(find.text('添加触发器'));
    await tester.pumpAndSettle();

    // 常规子页:当 / 触发函数(模式 + 函数名)/ 参数
    expect(find.text('常规'), findsOneWidget);
    expect(find.text('约束'), findsOneWidget);
    expect(find.text('当'), findsOneWidget);
    expect(find.text('触发函数'), findsOneWidget);
    expect(find.text('模式'), findsOneWidget);
    expect(find.text('函数名'), findsOneWidget);
    expect(find.text('可延迟'), findsNothing);

    await tester.tap(find.text('约束'));
    await tester.pumpAndSettle();
    expect(find.text('触发函数'), findsNothing);
    expect(find.text('可延迟'), findsOneWidget);
    expect(find.text('延迟'), findsOneWidget);
    expect(find.textContaining('延迟需先置「可延迟 = YES」'), findsOneWidget);

    // 切回常规:子页状态不影响网格
    await tester.tap(find.text('常规'));
    await tester.pumpAndSettle();
    expect(find.text('触发函数'), findsOneWidget);
  });

  testWidgets('选项标签含参考工具的字段集', (tester) async {
    wideView(tester);
    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();

    await openTab(tester, '选项');
    for (final label in ['不记录', '所有者', '表空间', '继承自', '填充因子 (%)', '集群']) {
      expect(find.text(label), findsOneWidget, reason: '选项页缺少: $label');
    }
    expect(
      tester.widget<CheckBox>(find.byType(CheckBox).first).enabled,
      isTrue,
    ); // 新建模式可编辑

    // 「继承自」的 `...` → 选父表弹窗
    await tester.tap(find.text('...'));
    await tester.pumpAndSettle();
    expect(find.text('选择继承的父表'), findsOneWidget);
    await tester.tap(find.text('取消'));
    await tester.pumpAndSettle();
    expect(find.text('选择继承的父表'), findsNothing);
  });

  testWidgets('编辑模式:选项页整页不开放(无对应 ALTER)', (tester) async {
    wideView(tester);
    await openEdit(tester, editHarness(loader: (db, t, s) async => readBack()));

    await openTab(tester, '选项');
    expect(find.text('不记录'), findsOneWidget);
    expect(tester.widget<CheckBox>(find.byType(CheckBox).first).enabled, isFalse);
    expect(tester.widget<IconBtn>(find.byType(IconBtn).last).onTap, isNull);
    expect(find.textContaining('无对应的 ALTER 语句'), findsOneWidget);
  });

  testWidgets('注释标签整区为编辑器(无标题与底部说明)', (tester) async {
    wideView(tester);
    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();

    await openTab(tester, '注释');
    expect(find.byType(Textarea), findsOneWidget);
    expect(find.text('表注释'), findsNothing);
    expect(find.text('输入表的注释…'), findsOneWidget);
  });

  testWidgets('系统目录候选注入后下拉用实际候选(而非静态兜底列表)', (tester) async {
    wideView(tester);
    // 故意取静态列表里没有的名字,避免与兜底候选混淆
    const seeded = DesignCandidates(
      collations: ['xx_YY.utf8'],
      opClasses: ['zz_pattern_ops'],
      tablespaces: ['zz_fast_storage'],
    );
    await tester.pumpWidget(ChangeNotifierProvider(
      create: (_) => AppState(),
      child: MaterialApp(
        home: Material(
          type: MaterialType.transparency,
          child: TableDesignerPage(
            title: '新建表',
            connection: '无此连接',
            database: 'db',
            candidatesLoader: (_) async => seeded,
          ),
        ),
      ),
    ));
    await tester.pumpAndSettle();

    bool offers(String name) => tester
        .widgetList<ComboBox<String>>(find.byType(ComboBox<String>))
        .any((c) => c.items.contains(name));

    // 字段页的「排序规则」:用实际目录,且保留首项空串 = 不指定
    expect(offers('xx_YY.utf8'), isTrue);
    expect(
      tester
          .widgetList<ComboBox<String>>(find.byType(ComboBox<String>))
          .firstWhere((c) => c.items.contains('xx_YY.utf8'))
          .items
          .first,
      '',
    );

    // 弹窗行来源是表字段:先建一个名为 amount 的字段
    await tester.tap(find.text('添加字段'));
    await tester.pumpAndSettle();
    await tester.enterText(
      find.descendant(
          of: find.byType(ListView), matching: find.byType(TextField)).first,
      'amount',
    );
    await tester.pumpAndSettle();

    // 索引属性面板的「表空间」由手输框升级为候选下拉
    await openTab(tester, '索引');
    await tester.tap(find.text('添加索引'));
    await tester.pumpAndSettle();
    await tester.tap(find.byIcon(Icons.arrow_right).first);
    await tester.pumpAndSettle();
    expect(offers('zz_fast_storage'), isTrue);

    // 「选择数据表字段」弹窗的「运算符类别」列取到候选
    await tester.tap(find.text('...').first);
    await tester.pumpAndSettle();
    expect(find.text('选择数据表字段'), findsOneWidget);
    expect(offers('zz_pattern_ops'), isTrue);
    await tester.tap(find.text('取消'));
    await tester.pumpAndSettle();

    // 选项页的「表空间」同样使用候选
    await openTab(tester, '选项');
    expect(offers('zz_fast_storage'), isTrue);
  });

  // ── 字段网格多选 / 复制粘贴 ────────────────────────────────

  /// 点字段网格第 [index] 行:落点在行首 ▶ 标记列,只触发行选中,
  /// 不会顺带改到单元格(输入框 / 勾选框 / 键列)
  Future<void> tapRow(WidgetTester tester, int index,
      {bool ctrl = false, bool shift = false}) async {
    final grid = tester.getRect(find.byType(ListView));
    // ListView 上下 padding 2,itemExtent 30
    final y = grid.top + 2 + index * 30 + 15;
    if (ctrl) await tester.sendKeyDownEvent(LogicalKeyboardKey.controlLeft);
    if (shift) await tester.sendKeyDownEvent(LogicalKeyboardKey.shiftLeft);
    await tester.tapAt(Offset(grid.left + 10, y));
    if (ctrl) await tester.sendKeyUpEvent(LogicalKeyboardKey.controlLeft);
    if (shift) await tester.sendKeyUpEvent(LogicalKeyboardKey.shiftLeft);
    await tester.pumpAndSettle();
  }

  /// 当前字段行数:每行只有「不是 null」一个勾选框
  int fieldRowCount(WidgetTester tester) => find
      .descendant(of: find.byType(ListView), matching: find.byType(CheckBox))
      .evaluate()
      .length;

  testWidgets('Ctrl 加选 / Shift 连选:工具栏按选中行数改文案', (tester) async {
    wideView(tester);
    await openEdit(tester, editHarness(loader: (db, t, s) async => readBack()));

    await tapRow(tester, 0);
    expect(fieldRowCount(tester), 2);
    expect(find.text('复制行'), findsOneWidget);

    await tapRow(tester, 1, ctrl: true);
    expect(find.text('复制 2 行'), findsOneWidget);

    // 再 Ctrl 点同一行 = 取消加选,回到单选
    await tapRow(tester, 1, ctrl: true);
    expect(find.text('复制行'), findsOneWidget);
  });

  testWidgets('多选行 → 复制为 Tab 分隔的整批字段(列序同网格表头)', (tester) async {
    wideView(tester);
    final clip = _ClipboardStub()..install(tester);
    await openEdit(tester, editHarness(loader: (db, t, s) async => readBack()));

    await tapRow(tester, 0);
    await tapRow(tester, 1, shift: true); // 锚点起连选成段
    await tester.tap(find.text('复制 2 行'));
    await tester.pumpAndSettle();

    expect(clip.text,
        'id\tint8\t64\t\t1\tPRI\t\nname\tvarchar\t32\t\t\t\t名称');
  });

  testWidgets('粘贴行:整批插入网格并进入 SQL 预览,占位空行被占用', (tester) async {
    wideView(tester);
    final clip = _ClipboardStub()
      ..text = 'amount\tdecimal(10,2)\t\t\t1\t\t金额\n'
          'remark\tvarchar\t64\t\t\t\t备注'
      ..install(tester);
    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();
    expect(fieldRowCount(tester), 1); // 新建表预置的空行

    await tester.tap(find.text('粘贴行'));
    await tester.pumpAndSettle();

    // 两行都进来,且粘贴结果整体成为选中区
    expect(fieldRowCount(tester), 2);
    expect(find.text('复制 2 行'), findsOneWidget);

    // 再复制回去:类型括号里的长度已拆进「长度 / 小数点」两格
    await tester.tap(find.text('复制 2 行'));
    await tester.pumpAndSettle();
    expect(clip.text,
        'amount\tdecimal\t10\t2\t1\t\t金额\nremark\tvarchar\t64\t\t\t\t备注');

    await openTab(tester, 'SQL 预览');
    final sql = previewSql(tester);
    expect(sql, contains('"amount" decimal(10,2) NOT NULL'));
    expect(sql, contains('COMMENT ON COLUMN'));
  });

  testWidgets('多选后「删除字段」整批删除,单选时只删一行', (tester) async {
    wideView(tester);
    await tester.pumpWidget(harness());
    await tester.pumpAndSettle();
    await tester.tap(find.text('添加字段'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('添加字段'));
    await tester.pumpAndSettle();
    expect(fieldRowCount(tester), 3);

    // 单选删一行
    await tapRow(tester, 1);
    await tester.tap(find.text('删除字段'));
    await tester.pumpAndSettle();
    expect(fieldRowCount(tester), 2);

    // 全选一次删掉
    await tapRow(tester, 0);
    await tapRow(tester, 1, shift: true);
    await tester.tap(find.text('删除字段'));
    await tester.pumpAndSettle();
    expect(fieldRowCount(tester), 0);
  });

  testWidgets('Ctrl+C / Ctrl+V 快捷键:焦点不在输入框时整批复制粘贴', (tester) async {
    wideView(tester);
    final clip = _ClipboardStub()..install(tester);
    await openEdit(tester, editHarness(loader: (db, t, s) async => readBack()));

    // 点行首标记列选中(不把焦点交给单元格输入框)
    await tapRow(tester, 0);
    await tapRow(tester, 1, shift: true);
    await tester.sendKeyDownEvent(LogicalKeyboardKey.controlLeft);
    await tester.sendKeyDownEvent(LogicalKeyboardKey.keyC);
    await tester.sendKeyUpEvent(LogicalKeyboardKey.keyC);
    await tester.sendKeyUpEvent(LogicalKeyboardKey.controlLeft);
    await tester.pumpAndSettle();

    expect(clip.text, contains('name\tvarchar\t32'));
  });

  testWidgets('字段行右键:不依赖焦点也能复制选中行', (tester) async {
    wideView(tester);
    final clip = _ClipboardStub()..install(tester);
    await openEdit(tester, editHarness(loader: (db, t, s) async => readBack()));

    final grid = tester.getRect(find.byType(ListView));
    await tester.tapAt(Offset(grid.left + 10, grid.top + 2 + 15),
        buttons: kSecondaryButton);
    await tester.pumpAndSettle();
    expect(find.text('复制行'), findsNWidgets(2)); // 工具栏 + 菜单项

    await tester.tap(find.text('复制行').last);
    await tester.pumpAndSettle();
    expect(clip.text, 'id\tint8\t64\t\t1\tPRI\t');
  });
}

/// 系统剪贴板桩:测试环境没有真实剪贴板,读写都落在这里
class _ClipboardStub {
  String text = '';

  void install(WidgetTester tester) {
    tester.binding.defaultBinaryMessenger
        .setMockMethodCallHandler(SystemChannels.platform, (call) async {
      switch (call.method) {
        case 'Clipboard.setData':
          text = (call.arguments as Map)['text'] as String? ?? '';
        case 'Clipboard.getData':
          return <String, String?>{'text': text};
      }
      return null;
    });
    addTearDown(() => tester.binding.defaultBinaryMessenger
        .setMockMethodCallHandler(SystemChannels.platform, null));
  }
}
